version: '2.13'

services:
  app:
    image: 'runflutterrun:latest'
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    volumes:
      - /tmp/uploads:/app/uploads
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:RunBackEndRun_User@db.ifvimggockdafddtsqqh.supabase.co:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=RunBackEndRun_User
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_PASSWORD=RunBackEndRun_User

  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=RunBackEndRun_User
      - POSTGRES_DB=runflutterrundb
